### PR TITLE
Scrutinizer cannot find coverage.xml

### PR DESCRIPTION
**Pull request by kagg-design**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6736

### CODE REVIEW

**Comment by andreasciamanna** [comment]
@kagg-design what should we do with this PR? Is it still valid?

**Comment by kagg-design** [comment]
@andreasciamanna Actually, PR is not needed. I have rebased it and, as you can see, it contains only changes in white spacing. I have no idea if we should merged it (as it was mentioned in the ticked) or just close.

**Comment by andreasciamanna** [comment]
@kagg-design I'll leave it to you: either option are fine to me.

**Comment by kagg-design** [comment]
Closed as obsolete.

**Pull request closed without merging**
